import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import {ClerkProvider} from '@clerk/nextjs'
import "./globals.css";
import { ToastProvider } from "@/components/providers/react-toast";
import { ReduxProvider } from "./store/provider";





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poppins = Poppins({ subsets: ['latin-ext'] , weight : ['100','200','300','400','500','600','700','800','900']})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
    <ClerkProvider> 
    <html lang="en">
      <body className={poppins.className} >
        <ReduxProvider>
      
      <ToastProvider/>
      
      {children}
      </ReduxProvider></body>
    </html>
    </ClerkProvider>
  );
}
